spring:
  freemarker:
    suffix: .html
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/babytun?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root
    virtual-host: /
    listener:
      simple:
        #定义消费者最多处理10个消息
        prefetch: 10
        #消息手动确认
        acknowledge-mode: manual
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
#    转换驼峰
    map-underscore-to-camel-case: true
server:
  port: 8080
